#
# .swiftlint.yml
# Created by Felix Mau (https://felix.hamburg)
#

opt_in_rules:
  - file_header

file_header:
  required_pattern: |
                    \/\/
                    \/\/  SWIFTLINT_CURRENT_FILENAME
                    \/\/  (GradientLoadingBar|Example|ExampleTests|ExampleSnapshotTests)
                    \/\/
                    \/\/  Created by .*? on \d{2}\.\d{2}\.\d{2}\.
                    \/\/  Copyright © \d{4} .*?\. All rights reserved\.
                    \/\/

included:
  - ./
  - ../GradientLoadingBar

excluded:
  - Pods

parent_config: Pods/SwiftConfigurationFiles/.swiftlint.yml